language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t skullcutter02/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true skullcutter02/react-test npm test

after_success:
  - docker build -t skullcutter02/multi-client ./client
  - docker build -t skullcutter02/multi-nginx ./nginx
  - docker build -t skullcutter02/multi-server ./server
  - docker build -t skullcutter02/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push skullcutter02/multi-client
  - docker push skullcutter02/multi-nginx
  - docker push skullcutter02/multi-server
  - docker push skullcutter02/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-740995310974"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
